{% set name = "flake8-plugin-utils" %}
{% set version = "1.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-plugin-utils-{{ version }}.tar.gz
  sha256: 39f6f338d038b301c6fd344b06f2e81e382b68fa03c0560dff0d9b1791a11a2c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flake8
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - flake8
    - python >=3.6,<4.0

test:
  imports:
    - flake8
    - flake8_plugin_utils
    - flake8_plugin_utils.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/flake8-plugin-utils
  summary: The package provides base classes and utils for flake8 plugin writing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
